#ifndef RUNTIME_CONFIG_H
#define RUNTIME_CONFIG_H

#ifndef GH_HEARTBEAT_INTERVAL_MS
#define GH_HEARTBEAT_INTERVAL_MS 30000
#endif

#ifndef GH_WIFI_RETRY_BASE_MS
#define GH_WIFI_RETRY_BASE_MS 1000
#endif

#ifndef GH_WIFI_RETRY_MAX_MS
#define GH_WIFI_RETRY_MAX_MS 30000
#endif

#ifndef GH_BOOTSTRAP_RETRY_BUDGET
#define GH_BOOTSTRAP_RETRY_BUDGET 5
#endif

#ifndef GH_WIFI_CONNECT_TIMEOUT_MS
#define GH_WIFI_CONNECT_TIMEOUT_MS 10000
#endif

#ifndef GH_MQTT_RETRY_BASE_MS
#define GH_MQTT_RETRY_BASE_MS 1000
#endif

#ifndef GH_MQTT_RETRY_MAX_MS
#define GH_MQTT_RETRY_MAX_MS 30000
#endif

#ifndef GH_MQTT_CONNECT_TIMEOUT_MS
#define GH_MQTT_CONNECT_TIMEOUT_MS 5000
#endif

#endif
